application: ascfpmfsrt
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.app
  login: required
  secure: always
- url: /feed/all
  script: main.app
  secure: optional

libraries:
- name: webapp2
  version: "latest"
- name: django
  version: "1.3"
