application: ascfpmfsrt
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.py
  login: required
  secure: always
