application: ascfpmfsrt
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

- url: /feed/all
  script: main.py
  secure: optional

- url: /.*
  script: main.py
  login: required
  secure: always